# Generated by Django 5.0.3 on 2024-03-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_email_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="email_verified",
            new_name="email_confirmed",
        ),
    ]
