# Generated by Django 5.0.3 on 2024-03-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="prize name")),
                ("age", models.IntegerField(max_length=100, verbose_name="age")),
                ("category", models.CharField(max_length=100, verbose_name="category")),
                (
                    "info",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="info"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prize list",
                "db_table": "Prize",
                "ordering": ("id",),
            },
        ),
    ]
