# Generated by Django 5.0.3 on 2024-03-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mukofotlar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prize",
            name="age",
            field=models.IntegerField(verbose_name="age"),
        ),
        migrations.AlterField(
            model_name="prize",
            name="image",
            field=models.ImageField(upload_to="prizes", verbose_name="Prize image"),
        ),
    ]
