# Generated by Django 5.0.3 on 2024-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mukofotlar", "0002_alter_prize_age_alter_prize_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prize",
            name="age",
            field=models.CharField(max_length=200, verbose_name="age"),
        ),
    ]
