# Generated by Django 5.0.3 on 2024-03-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mukofotlar", "0003_alter_prize_age"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prize",
            options={"ordering": ("-id",), "verbose_name": "Prize list"},
        ),
        migrations.AlterField(
            model_name="prize",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pri/%Y/%m/%d",
                verbose_name="Prize image",
            ),
        ),
    ]
